CREATE TABLE UF(
  CodigoUF SERIAL PRIMARY KEY,
  SIGLA VARCHAR(2) NOT NULL UNIQUE,
  NomeUF VARCHAR(80) NOT NULL UNIQUE
);

-- cidade = {CodigoCidade, NomeCidade, FKCodigoUF}
CREATE TABLE CIDADE(
  CodigoCidade SERIAL PRIMARY KEY,
  NomeCidade VARCHAR(80) NOT NULL UNIQUE,

  FKCodigoUF INTEGER REFERENCES UF(CodigoUF)
);

-- VIEWS

CREATE VIEW DADOS_CIDADE AS
SELECT C.CodigoCidade, C.NomeCidade, UF.NomeUF
FROM CIDADE C, UF
WHERE C.FKCodigoUF = UF.CodigoUF;
---------------------------------------------------------------------
CREATE DATABASE EXEMPLO_VIEWS;

CREATE TABLE MARCA(
	CODMARCA SERIAL PRIMARY KEY,
  NOMEMARCA VARCHAR(80) NOT NULL UNIQUE
);
CREATE TABLE TIPO(
	CODTIPO SERIAL PRIMARY KEY,
  NOMETIPO VARCHAR(80) NOT NULL UNIQUE
);
CREATE TABLE PRODUTO(
	CODPRODUTO SERIAL PRIMARY KEY,
  NOMEPRODUTO VARCHAR(80) NOT NULL UNIQUE,
  VALOR NUMERIC(10,2) NOT NULL,
  QUANTIDADE NUMERIC(10,2) NOT NULL,
  CODMARCA_FK INTEGER REFERENCES MARCA(CODMARCA),
  CODTIPO_FK INTEGER REFERENCES TIPO(CODTIPO)
  );
CREATE TABLE CLIENTE(
  CODCLIENTE SERIAL PRIMARY KEY,
  NOMECLIENTE VARCHAR(80) NOT NULL
);
CREATE TABLE VENDA(
  CODVENDA SERIAL PRIMARY KEY,
  DATAVENDA DATE NOT NULL,
  CODCLIENTE_FK INTEGER REFERENCES CLIENTE(CODCLIENTE)
);
CREATE TABLE ITENS_VENDA(
  CODVENDA_FK INTEGER REFERENCES VENDA(CODVENDA),
  CODPRODUTO_FK INTEGER REFERENCES PRODUTO(CODPRODUTO),

  VALORVENDA NUMERIC(10,2) NOT NULL,
  QUANTIDADE NUMERIC(10,2) NOT NULL
);

ALTER TABLE ITENS_VENDA
ADD CONSTRAINT PK_COMPOSTA PRIMARY KEY (CODVENDA_FK,CODPRODUTO_FK);

CREATE VIEW DADOS_PRODUTOS AS
SELECT P.NOMEPRODUTO, P.VALOR, P.QUANTIDADE, M.NOMEMARCA, T.NOMETIPO
FROM PRODUTO P, MARCA M, TIPO T
WHERE P.CODMARCA_FK = M.CODMARCA
AND P.CODTIPO_FK = T.CODTIPO;

SELECT * FROM DADOS_PRODUTOS;

-- RETORNE OS PRODUTOS VENDIDOS EM UMA VENDA COM O SUBTOTAL
SELECT (I.QUANTIDADE * I.VALORVENDA) AS SUBTOTAL, P.NOMEPRODUTO
FROM ITENS_VENDA I, PRODUTO P
WHERE I.CODPRODUTO_FK = P.CODPRODUTO

-- CRIANDO A VIEW ITENS
CREATE VIEW ITENS AS
SELECT (I.QUANTIDADE * I.VALORVENDA) AS SUBTOTAL, P.NOMEPRODUTO
FROM ITENS_VENDA I, PRODUTO P
WHERE I.CODPRODUTO_FK = P.CODPRODUTO


-- IMPORTANTE!!!
SELECT * FROM ITENS
WHERE CODVENDA_FK = 1;

--ERRO
DROP VIEW ITENS;


CREATE VIEW ITENS AS
SELECT I.CODVENDA_FK, (I.QUANTIDADE * I.VALORVENDA) AS SUBTOTAL, P.NOMEPRODUTO
FROM ITENS_VENDA I, PRODUTO P
WHERE I.CODPRODUTO_FK = P.CODPRODUTO

-- IMPORTANTE!!!
SELECT * FROM ITENS
WHERE CODVENDA_FK = 1;


















