create database aula_1502;

-- curso = {COD_CURSO, NOME_CURSO}
create table CURSO(
	COD_CURSO SERIAL PRIMARY KEY,
	NOME_CURSO VARCHAR(80) NOT NULL UNIQUE
);
-- sexo  = {COD_SEXO, NOME_SEXO}
create table SEXO(
	COD_SEXO SERIAL PRIMARY KEY,
	NOME_SEXO VARCHAR(80) NOT NULL UNIQUE
);
-- rua = {COD_RUA, NOME_RUA}
create table RUA(
	COD_RUA SERIAL PRIMARY KEY,
	NOME_RUA VARCHAR(80) NOT NULL UNIQUE
);
-- bairro = {COD_BAIRRO, NOME_BAIRRO}
create table BAIRRO(
	COD_BAIRRO SERIAL PRIMARY KEY,
	NOME_BAIRRO VARCHAR(80) NOT NULL UNIQUE
);
-- cep = {COD_CEP, NUMERO_CEP}
create table CEP(
	COD_CEP SERIAL PRIMARY KEY,
	NUMERO_CEP CHAR(9) NOT NULL UNIQUE
);
-- estado = {COD_ESTADO, NOME_ESTADO, SIGLA}
create table ESTADO(
	COD_ESTADO SERIAL PRIMARY KEY,
	NOME_ESTADO VARCHAR(80) NOT NULL UNIQUE,
	SIGLA CHAR(2) NOT NULL UNIQUE
);
-- cidade =  {COD_CIDADE, NOME_CIDADE, COD_ESTADO_FK}
create table CIDADE(
	COD_CIDADE SERIAL PRIMARY KEY,
	NOME_CIDADE VARCHAR(80) NOT NULL UNIQUE,
	COD_ESTADO_FK INTEGER REFERENCES ESTADO(COD_ESTADO)
	MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE
);
-- aluno = {COD_ALUNO, NOME_ALUNO, COD_SEXO_FK, COD_CURSO_FK
--	    COD_RUA_FK, COD_BAIRRO_FK, COD_CEP_FK, COD_CIDADE_FK}
create table ALUNO(
	COD_ALUNO SERIAL PRIMARY KEY,
	NOME_ALUNO VARCHAR(80) NOT NULL,
	COD_SEXO_FK INTEGER REFERENCES SEXO(COD_SEXO)
	MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE,
	COD_CURSO_FK INTEGER REFERENCES CURSO(COD_CURSO)
	MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE,
	COD_RUA_FK INTEGER REFERENCES RUA(COD_RUA)
	MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE,
	COD_BAIRRO_FK INTEGER REFERENCES BAIRRO(COD_BAIRRO)
	MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE,
	COD_CEP_FK INTEGER REFERENCES CEP(COD_CEP)
	MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE,
	COD_CIDADE_FK INTEGER REFERENCES CIDADE(COD_CIDADE)
	MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE
);

-- curso = {COD_CURSO, NOME_CURSO}
insert into CURSO(NOME_CURSO) VALUES ('ADS');
insert into CURSO(NOME_CURSO) VALUES ('ENFERMAGEM');
insert into CURSO(NOME_CURSO) VALUES ('MEDICINA');
insert into CURSO(NOME_CURSO) VALUES ('AGRONOMIA');

select * from CURSO

-- sexo  = {COD_SEXO, NOME_SEXO}
insert into SEXO(NOME_SEXO) VALUES ('MASCULINO');	
insert into SEXO(NOME_SEXO) VALUES ('FEMININO');

-- rua = {COD_RUA, NOME_RUA}
insert into RUA(NOME_RUA) VALUES ('XV DE NOVEMBRO');
insert into RUA(NOME_RUA) VALUES ('PASSEIO GOIANIA');

-- bairro = {COD_BAIRRO, NOME_BAIRRO}
insert into BAIRRO(NOME_BAIRRO) values ('CENTRO');
insert into BAIRRO(NOME_BAIRRO) values ('JARDIM AEROPORTO');

-- cep = {COD_CEP, NUMERO_CEP}
insert into CEP(NUMERO_CEP) values ('15385-000');
insert into CEP(NUMERO_CEP) values ('15775-000');

-- estado = {COD_ESTADO, NOME_ESTADO, SIGLA}
insert into ESTADO(NOME_ESTADO, SIGLA) values ('SÃO PAULO', 'SP');
insert into ESTADO(NOME_ESTADO, SIGLA) values ('MINAS GERAIS', 'MG');

-- cidade =  {COD_CIDADE, NOME_CIDADE, COD_ESTADO_FK}
insert into CIDADE(NOME_CIDADE, COD_ESTADO_FK) values ('SANTA FÉ DO SUL', 1);
insert into CIDADE(NOME_CIDADE, COD_ESTADO_FK) values ('ITURAMA', 1);

SELECT * FROM CIDADE;


-- aluno = {COD_ALUNO, NOME_ALUNO, COD_SEXO_FK, COD_CURSO_FK
--	    COD_RUA_FK, COD_BAIRRO_FK, COD_CEP_FK, COD_CIDADE_FK}

insert into ALUNO
(NOME_ALUNO,COD_SEXO_FK, COD_CURSO_FK, COD_RUA_FK,
COD_BAIRRO_FK, COD_CEP_FK, COD_CIDADE_FK)
values 
('GERMANO', 3, 1, 3, 3, 1, 2);

SELECT * FROM SEXO 
 































