create database ATIVIDADE_PRODUTO;

-- MARCA = {COD_MARCA, NOME_MARCA, DESCRICAO}
create table MARCA(
	COD_MARCA SERIAL PRIMARY KEY,
	NOME_MARCA VARCHAR(80) NOT NULL UNIQUE
);
---------------------------------------------------------------

---ADCIONE UMA COLUNA CHAMADA DESCRIÇÃO QUE NÃO PODE CONTER VALORES NULOS.
ALTER TABLE MARCA ADD 
COLUMN DESCRICAO VARCHAR(80) NOT NULL 
DEFAULT 'COLOQUE UMA INFORMAÇÃO AQUI';



-- TIPO = {COD_TIPO, NOME_TIPO}
create table TIPO(
	COD_TIPO SERIAL PRIMARY KEY,
	NOME_TIPO VARCHAR(80) NOT NULL UNIQUE
);
------------------------------------------------------------------


-- PRODUTO = 	{COD_PRODUTO, NOME_PRODUTO
--		 QUANTIDADE, VALOR_UNITARIO
--		 COD_MARCA_FK, COD_TIPO_FK}
create table PRODUTO(
	COD_PRODUTO SERIAL PRIMARY KEY,
	NOME_PRODUTO VARCHAR(80) NOT NULL,
	QUANTIDADE NUMERIC(12) NOT NULL,
	VALOR_UNITARIO NUMERIC(10, 2) NOT NULL,

	COD_MARCA_FK INTEGER REFERENCES MARCA(COD_MARCA)
	MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE,
	COD_TIPO_FK INTEGER REFERENCES TIPO(COD_TIPO)
	MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE
);
-----------------------------------------------------------------


---INSIRA PELO MENOS 6 REGISTROS NA TABELA MARCA;
-- MARCA = {COD_MARCA, NOME_MARCA}
INSERT INTO MARCA(NOME_MARCA, DESCRICAO)
VALUES ('ARISCO', 'PRODUTOS DE ALTA QUALIDADE');

INSERT INTO MARCA(NOME_MARCA, DESCRICAO)
VALUES ('KINIMO', 'COSMÉTICOS');

INSERT INTO MARCA(NOME_MARCA, DESCRICAO)
VALUES ('BURGER KING', 'LANCHES');

INSERT INTO MARCA(NOME_MARCA, DESCRICAO)
VALUES ('COCA_COLA', 'REFRIGEREANTE');

INSERT INTO MARCA(NOME_MARCA, DESCRICAO)
VALUES ('SADIA', 'Lasanha, nuggets, pizza e hot pocket');

INSERT INTO MARCA(NOME_MARCA, DESCRICAO)
VALUES ('DANONE', 'BEBIDAS LÁCTEAS');

SELECT * FROM MARCA;
--1;"ARISCO"
--2;"KINIMO"
--3;"BURGER KING"
--4;"COCA_COLA"
--5;"SADIA"
--6;"DANONE"

-- TIPO = {COD_TIPO, NOME_TIPO}
INSERT INTO TIPO(NOME_TIPO)
VALUES ('ALIMENTÍCIO');

INSERT INTO TIPO(NOME_TIPO)
VALUES ('HIGIÊNICO');

SELECT * FROM TIPO;
--1;"ALIMENTÍCIO"
--2;"HIGIÊNICO"



---ATUALIZE PELO MENOS DOIS CAMPOS NESTA TABELA;
UPDATE TIPO SET NOME_TIPO = 'HIGIÊNI PESSOAL'
WHERE NOME_TIPO = 'HIGIÊNI';
--1;"ALIMENTÍCIO"
--2;"HIGIÊNI PESSOAL"

UPDATE TIPO SET NOME_TIPO = 'ALIMENTOS'
WHERE COD_TIPO = 1;
--1;"ALIMENTOS"
--2;"HIGIÊNI PESSOAL"



---APAGUE OS REGISTROS QUE POSSUAM NO NOME DO TIPO COMEÇADOS PELA LETRA 'E’;
INSERT INTO TIPO(NOME_TIPO)
VALUES ('ELETRONICO');

SELECT * FROM TIPO;
--1;"ALIMENTÍCIO"
--2;"HIGIÊNI PESSOAL"
--3;"ELETRONICO"

DELETE FROM TIPO 
WHERE NOME_TIPO 
LIKE 'E%';

SELECT * FROM TIPO;


-- PRODUTO = 	{COD_PRODUTO, NOME_PRODUTO
--		 QUANTIDADE, VALOR_UNITARIO
--		 COD_MARCA_FK, COD_TIPO_FK}
-- MARCA  =
--1;"ARISCO"
--2;"KINIMO"
--3;"BURGER KING"
--4;"COCA_COLA"
--5;"SADIA"
--6;"DANONE"
--TIPO =
--1;"ALIMENTÍCIO"
--2;"HIGIÊNI PESSOAL"
INSERT INTO PRODUTO(NOME_PRODUTO, QUANTIDADE, VALOR_UNITARIO,
		    COD_MARCA_FK, COD_TIPO_FK)
		VALUES ('MACARRÃO', 100, 3.98, 1, 1);
INSERT INTO PRODUTO(NOME_PRODUTO, QUANTIDADE, VALOR_UNITARIO,
		    COD_MARCA_FK, COD_TIPO_FK)
		    VALUES('CAFÉ', 50, 9.99, 1, 1);
INSERT INTO PRODUTO(NOME_PRODUTO, QUANTIDADE, VALOR_UNITARIO,
		    COD_MARCA_FK, COD_TIPO_FK)
		    VALUES('ARROZ', 400, 5.55, 1, 1);
INSERT INTO PRODUTO(NOME_PRODUTO, QUANTIDADE, VALOR_UNITARIO,
		    COD_MARCA_FK, COD_TIPO_FK)
		    VALUES('DANONE', 30, 3.58, 6, 1);
INSERT INTO PRODUTO(NOME_PRODUTO, QUANTIDADE, VALOR_UNITARIO,
		    COD_MARCA_FK, COD_TIPO_FK)
		    VALUES('BOLACHA', 60, 2.50, 2, 1);
INSERT INTO PRODUTO(NOME_PRODUTO, QUANTIDADE, VALOR_UNITARIO,
		    COD_MARCA_FK, COD_TIPO_FK)
		    VALUES('PAPEL HIGIÊNICO', 50, 25.50, 2, 2);
INSERT INTO PRODUTO(NOME_PRODUTO, QUANTIDADE, VALOR_UNITARIO,
		    COD_MARCA_FK, COD_TIPO_FK)
		    VALUES('BOLO', 60, 9.50, 2, 1);



---3 AUMENTE OS VALORES EM 10% DE TODOS OS PRODUTOS DO TIPO ‘ALIMENTÍCIO’;
UPDATE PRODUTO 
SET VALOR_UNITARIO = VALOR_UNITARIO * 1.1
WHERE COD_TIPO_FK = (SELECT COD_TIPO FROM TIPO WHERE NOME_TIPO = 'ALIMENTÍCIO');

SELECT * FROM PRODUTO;

--6;"PAPEL HIGIÊNICO"
--1;"MACARRÃO"
--2;"CAFÉ"
--3;"ARROZ"
--5;"BOLACHA"
--4;"DANONE"


--- 4. MOSTRE OS DADOS DOS PRODUTOS SUBSTITUINDO OS VALORES DAS CHAVES 
-- ESTRANGEIRAS PELOS NOMES PROPRIAMENTE DITOS
SELECT P.NOME_PRODUTO, P.QUANTIDADE, M.NOME_MARCA, TIPO.NOME_TIPO
FROM PRODUTO P, MARCA M, TIPO
WHERE M.COD_MARCA = P.COD_MARCA_FK
AND TIPO.COD_TIPO = P.COD_TIPO_FK;



---5. LISTE A QUANTIDADE DE PRODUTOS QUE SÃO DA MARCA ‘ARISCO’ E POSSUAM O 
--VALOR UNITÁRIO MAIOR QUE R$ 100,00.

UPDATE PRODUTO
SET VALOR_UNITARIO = 150
WHERE COD_PRODUTO = 4;

UPDATE PRODUTO
SET COD_MARCA_FK = 1
WHERE COD_PRODUTO = 4;

SELECT CONT(P.COD_PRODUTO)
AS P.QUANTIDADE
FROM PRODUTO P, MARCA M
WHERE P.VALOR_UNITARIO>100
AND M.NOME_MARCA


SELECT P.NOME_PRODUTO, M.NOME_MARCA, P.VALOR_UNITARIO
FROM PRODUTO P, MARCA M
WHERE M.COD_MARCA = P.COD_MARCA_FK
AND P.VALOR_UNITARIO > 100
AND M.NOME_MARCA = 'ARISCO';


---6. MOSTRE O PRODUTO COM O MAIOR VALOR REGISTRADO;
SELECT MAX(VALOR_UNITARIO)
FROM PRODUTO;



---7. IMPRIMA OS DADOS DE TODOS OS PRODUTOS QUE COMECEM COM A LETRA ‘B’, 
--TENHAM A MARCA ‘KININO’ E SEJAM PRODUTOS ‘ALIMENTOS’;
SELECT P.NOME_PRODUTO, M.NOME_MARCA, T.NOME_TIPO
FROM PRODUTO P, MARCA M, TIPO T
WHERE M.NOME_MARCA = 'KINIMO'
AND T.NOME_TIPO = 'ALIMENTOS' 
AND P.NOME_PRODUTO LIKE 'B%';


---8. INFORME O VALOR TOTAL DE CADA ITEM REGISTRADO (VALORUNITÁRIO * 
--QUANTIDADE);

SELECT P.NOME_PRODUTO, (P.QUANTIDADE * P.VALOR_UNITARIO)
AS SOMA
FROM PRODUTO P;


---9. INFORME O VALOR TOTAL EM ESTOQUE DA LOJA. (SOMA DE TODOS OS ELEMENTOS 
--DO EXERCÍCIO 8

SELECT SUM(P.QUANTIDADE * P.VALOR_UNITARIO)
AS SOMA_DE_TODOS_OS_ELEMENTOS_DO_EXERCICIO_8
FROM PRODUTO P;
















