CREATE DATABASE COMERCIO2;

--CRIAR UM DOMÍNIO
CREATE DOMAIN C_NOMES VARCHAR(80) NOT NULL;

-- MARCA = {COD_MARCA, NOME_MARCA}
CREATE TABLE MARCA(
	COD_MARCA SERIAL PRIMARY KEY,
	NOME_MARCA VARCHAR(80) NOT NULL	
);
-- ALTER TABLE <NOME TABELA> ALTER COLUMN TIPO;
-- ALTERAR O TIPO DE UMA COLUNA
ALTER TABLE MARCA
ALTER COLUMN NOME_MARCA 
TYPE VARCHAR(40);

-- CRIAR UMA NOVA COLUNA
ALTER TABLE MARCA
ADD COLUMN DESCRICAO
VARCHAR(80);

ALTER TABLE MARCA
ADD COLUMN VALOR_MARCA
NUMERIC(10, 2) NOT NULL DEFAULT 0.00;

-- INSERIR UMA MARCA
INSERT INTO MARCA(NOME_MARCA, VALOR_MARCA)
VALUES ('NIKE', 100.00);
--2;"NIKE";100.00;""
INSERT INTO MARCA(NOME_MARCA, VALOR_MARCA)
VALUES ('ADIDAS', 500.00);


-- INSERINDO INFORMAÇÃO
UPDATE MARCA
SET VALOR_MARCA = 50.0
WHERE NOME_MARCA = 'NIKE';

-- ALTERANDO MAIS DE COLUNA POR VEZ
ALTER TABLE MARCA
ALTER COLUMN NOME_MARCA TYPE VARCHAR(100),
ALTER COLUMN DESCRICAO TYPE VARCHAR(200);

-- MUDANDO O NOME DA COLUNA 
ALTER TABLE MARCA
RENAME COLUMN NOME_MARCA
TO NOME_MARCAS;

-- MUDANDO O NOME DA TABELA
ALTER TABLE MARCA
RENAME TO MARCAS;

--DELETANDO TABELA
DELETE FROM MARCAS;

-- MUDANDO ATRIBUTOS
ALTER TABLE MARCAS
ALTER COLUMN NOME_MARCAS
SET NOT NULL,
ALTER COLUMN DESCRICAO
SET NOT NULL;

-- INSERINDO UMA MARCA
INSERT INTO MARCAS(NOME_MARCAS, VALOR_MARCA, DESCRICAO)
VALUES('NIKE', 100.0, 'NEYMAR');

-- REMOVENDO RESTRIÇÃO DE ATRIBUTOS
ALTER TABLE MARCAS
ALTER COLUMN DESCRICAO 
DROP NOT NULL;

-- VERIFICAR O TAMANHO DE UM CAMPO
ALTER TABLE MARCAS
ADD CONSTRAINT CHK_DESCRICAO
CHECK (CHAR_LENGTH(DESCRICAO) > 2);


--DEFININDO UMA CHAVE
CREATE TABLE TESTE(
	COD_TESTE NOT NULL;
);
ALTER TABLE TESTE 
ADD PRIMARY KEY(COD_TESTE)

-- ADD CAMPO CHAVE ESTRANGEIRA
ALTER TABLE TESTE 
ADD COLUMN COD_MARCA_FK INTEGER;

ALTER TABLE TESTE 
ADD CONSTRAINT COD_MA

SELECT * FROM MARCAS;











